#define DMV_VEHICLE             (1)
#define DMV_HELICOPTER          (2)
#define WITHSIGNAL_CAR          (3)
#define DMV_TAXI                (4)
#define RENT_CAR                (5)
#define PIZZA_CAR               (6)
#define TAXI_CAR                (7)
#define TRUCK_CAR               (8)
#define MECHANIC_CAR            (9)
#define LAMBERJACK_CAR          (10)
#define TRASHMASTER_CAR         (11)
#define MINER_CAR               (12)


#define MAX_HEALTH_VEHICLE      (750.0)

#define IMPOUND_FEE             (1500)


#define JACKING_TIME             (600)

#define BLOCK_NONE 0
#define LESS_DAMAGE_FIST 1
#define BLOCK_FIST 2
#define LESS_DAMAGE_MELEE 3
#define BLOCK_PHYSICAL 4