new fd_skins[] = {274, 275, 276, 277, 278, 279, 308, 305, 309, 311, 304, 303};

new attach_fd_model[] = {19330,19331,19942,11736,11738,18634,18641,19472,19559,19904,1008,11745,18875};
new bort_list_fd[17] = {1997, 2146, 19944, 3799, 2772, 12950, 18728, 18725, 18690, 19836, 2411, 1366, 1448, 19834, 1238, 1228, 1459};

new attach_fd_name[][] =
{
	"Yellow helmet",
	"Black helmet",
	"Walkie-talkie",
	"First aid kit",
	"BLS bag",
	"Scrap",
	"Lantern",
	"Respirator",
	"Backpack",
	"Orange vest",
	"Balloon",
	"Bag with things",
	"Pager"
};

new bort_names_fd[17][32] =
{
	"Gurney",
	"Gurney 2",
	"Package with a corpse",
	"Suicide box",
	"Stairs",
	"Ladder 2",
	"Signal Torch",
	"Smoke particles",
	"Particles of Fire",
	"Blood stain",
	"Maniken",
	"Hydrant",
	"Fixer",
	"Tape",
	"Cone",
	"Barrier",
	"Barrier 2"
};