#define     MAX_ORE_TYPES   (6)
#define     MAX_VEINS       (128)
#define     MAX_ORES        (256)

#define     UPDATE_RATE     (500)		// update rate of mining in miliseconds, higher the value longer the mining time (default: 200)
#define     BAR_MAX         (25.0)		// maximum value of the progress bar, higher the value longer the mining time (default: 15.0)
#define     VEHICLE_LIMIT   (8)			// how many ores someone can store in their vehicle (default: 8)
#define     ATTACH_INDEX    (3)			// setplayerattachedobject index

#define     REGEN_TIME    	(45)        // how many minutes before respawning veins (default: 45)
#define     ORE_TIME        (5)         // how many minutes before destroying a dropped ore (default: 5)
