#define TRUCKER_FUEL 		0 //Vehicle
#define TRUCKER_FOOD		1
#define TRUCKER_DRINK 		2
#define TRUCKER_CLOTHES 	3
#define TRUCKER_CARS 		4 //Vehicle
#define TRUCKER_FURNITURE   5
#define TRUCKER_MEAT        6
#define TRUCKER_EGGS        7
#define TRUCKER_MILK 		8 //Vehicle
#define TRUCKER_CEREAL      9 //Vehicle
#define TRUCKER_COTTON      10 //Vehicle
#define TRUCKER_DYES        11 //Vehicle
#define TRUCKER_COMPONENTS  12
#define TRUCKER_MALT        13 //Vehicle
#define TRUCKER_MONEY       14
#define TRUCKER_PAPER       15
#define TRUCKER_AGGREGATE   16 //Vehicle
#define TRUCKER_WOODS	 	17 //Vehicle
#define TRUCKER_GUNPOWDER   18
#define TRUCKER_SCRAP       19 //Vehicle
#define TRUCKER_STEEL       20
#define TRUCKER_GUNS        21
#define TRUCKER_BRICKS 		22 //Vehicle
#define TRUCKER_APPLIANCES  23
#define TRUCKER_FRUITS      24

#define PAGE_NEXT           (0)
#define PAGE_PREV           (1)