#define FLOAT_ITEMS         65..67,103..118

#define ITEM_TYPE_NONE              (0)
#define ITEM_TYPE_WEAPON            (1)
#define ITEM_TYPE_SEEDS             (2)
#define ITEM_TYPE_FOOD              (3)
#define ITEM_TYPE_DRUGS             (4)
#define ITEM_TYPE_MISC              (5)
#define ITEM_TYPE_REACT             (6)
#define ITEM_TYPE_INSIDEABLE_OBJECT (7)
#define ITEM_TYPE_AMMO              (8)

#define ITEM_SIZE_NONE              (0)
#define ITEM_SIZE_SMALL             (1)
#define ITEM_SIZE_MEDIUM            (2)
#define ITEM_SIZE_BIG               (3)
#define ITEM_SIZE_VBIG              (4)

#define INV_SIGN    		19
#define INV_RADIO   		20
#define INV_MASK    		21
#define INV_BURGER      	35
#define INV_PIZZA       	36
#define INV_CHICKEN     	37
#define INV_HOTDOG      	38
#define INV_GASCAN      	39
#define INV_BOOMBOX     	40
#define INV_SILENCER    	44
#define INV_OPTICS      	45
#define INV_LIGHTER     	47
#define INV_CIGAR       	48
#define INV_DICE        	49
#define INV_CARDS       	50
#define INV_PEN         	51
#define INV_PICKLOCK       	52
#define INV_SHELL        	53
#define INV_POWDER			54
#define INV_BODYBAG   		55
#define INV_BEER        	56
#define INV_VODKA       	57
#define INV_COLA        	58
#define INV_WATER       	59
#define INV_WHISKEY     	60
#define INV_BRANDY      	61
#define INV_SODA        	62
#define INV_WINE        	63
#define INV_MED_GANJA       65

#define INV_GANJA           66
#define INV_COCA            115
#define INV_POPPY           116

#define INV_DRUG            67

#define INV_LSD             67
#define INV_MET             68
#define INV_HEROIN          69
#define INV_COCAINE         70
#define INV_EPHEDRINE       71
#define INV_DIETHYL         72
#define INV_ALKALI          73
#define INV_ACID            74

#define INV_HEAL            75
#define INV_CARSOUND        76
#define INV_SKATE        	77
#define INV_PIZZA_BOX       78
#define INV_CHICKEN_BOX     79

#define INV_SEED_GANJA	   	64
#define INV_SEED_COCA       80
#define INV_SEED_POPPY      81

#define INV_TOOLS       	100
#define INV_FAKENUM       	101