/* Обозначения работ */

#define JOBLESS             (0)
#define JOB_TRUCKER         (1)
#define JOB_MECHANIC        (2)
#define JOB_TAXI            (3)
#define JOB_DRUGDEALER      (4)
#define JOB_GUNDEALER       (5)
#define JOB_PIZZA           (6)
#define JOB_CARJACKER       (7)
#define JOB_LAMBERJACKER    (8)
#define JOB_TRASHMASTER     (9)
#define JOB_MINER           (10)


#define GetJobName(%0) jobs_names[%0]

#define MISSION_NONE		0
#define CARJACKER_DELIVER 	1
#define CARJACKER_DROPOFF 	2

#define BLACKMARKET_X   2705.23
#define BLACKMARKET_Y   -2550.89
#define BLACKMARKET_Z   13.634