new city_skins[] = {147, 186, 187, 295, 17, 91, 93, 141, 150};

new attach_city_model[] = {19904,19142,19515,18636,19161,19162,19521,19098,19200,19776,19777,18875,19942};
new bort_list_city[4] = {19834, 1238, 1228, 1459};

new attach_city_name[][] =
{
	"Orange vest",
	"Black body armor",
	"Gray bulletproof vest",
	"Police cap # 1",
	"Police cap # 2",
	"Police cap number 3",
	"Police cap",
	"Police Hat",
	"Police motorcycle helmet",
	"FBI Card",
	"FBI Logo",
	"Pager",
	"Walkie-talkie"
};

new bort_names_city[4][32] =
{
	"Tape",
	"Cone",
	"Barrier",
	"Barrier 2"
};