#include <gm/a_build/mapping_build.inc>
#include <gm/a_build/def_build.inc>
#include <gm/a_build/var_build.inc>
#include <gm/a_build/enum_build.inc>
#include <gm/lockjob/locksystem.inc>
#include <gm/a_build/func_build.inc>
#include <gm/a_build/misc_build.inc>
#include <gm/a_build/cmd_build.inc>
#include <gm/a_build/dlg_build.inc>
#include <gm/a_build/mode_build.inc>
#include <gm/a_build/timer_build.inc>

#include <gm/mapping/lswpack.inc>
///////////////////////////////////////
///////////////////////////////////////

///////////////////////////////////////
/////////	EXTERIORS	///////////////
///////////////////////////////////////
//#include <gm/mapping/exteriors.inc>

