#include <gm/admin/tester_cmd.inc>
#include <gm/admin/admin1_cmd.inc>
#include <gm/admin/admin2_cmd.inc>
#include <gm/admin/admin3_cmd.inc>
#include <gm/admin/admin4_cmd.inc>
#include <gm/admin/admin5_cmd.inc>

#include <gm/animations/anim_cmd.inc>
#include <gm/attach/attach_cmd.inc>

#include <gm/bank/bank_cmd.inc>
#include <gm/boombox/box_cmd.inc>
#include <gm/cctv/cctv_cmd.inc>
#include <gm/death/death_cmd.inc>
#include <gm/drugs/drugs_cmd.inc>
#include <gm/gps/gps_cmd.inc>
#include <gm/food/food_cmd.inc>

#include <gm/factions/f_cmd.inc>
#include <gm/factions/docs/docs_cmd.inc>
#include <gm/factions/fd/fd_cmd.inc>
#include <gm/factions/san/san_cmd.inc>
#include <gm/factions/sasd/sasd_cmd.inc>

#include <gm/prop/prop_cmd.inc>
#include <gm/prop/b/biz_cmd.inc>
#include <gm/prop/d/door_cmd.inc>
#include <gm/prop/g/garage_cmd.inc>
#include <gm/prop/h/house_cmd.inc>
#include <gm/prop/f/furn_cmd.inc>

#include <gm/prop/v/veh_cmd.inc>
#include <gm/prop/v/park_cmd.inc>
//#include <gm/streets/st_cmd.inc> 0 cmds

#include <gm/inventory/inv_cmd.inc>
#include <gm/items/drop_cmd.inc>

#include <gm/chopshop/chopshop_cmd.inc>
#include <gm/billboard/bb_cmd.inc>

#include <gm/job/job_cmd.inc>
#include <gm/job/trash/trash_cmd.inc>
#include <gm/job/mech/mech_cmd.inc>
#include <gm/job/lamber/lam_cmd.inc>
#include <gm/job/fisher/fish_cmd.inc>
#include <gm/job/miner/miner_cmd.inc>
#include <gm/job/pizza/pizza_cmd.inc>
#include <gm/job/taxi/taxi_cmd.inc>
#include <gm/job/trucker/trucker_cmd.inc>
#include <gm/job/vjacker/vjacker_cmd.inc>
#include <gm/job/truck2/trucker.inc>
#include <gm/speedcam/sc_cmd.inc>
#include <gm/licenses/lic_cmd.inc>
#include <gm/notes/notes_cmd.inc>
#include <gm/players/pl_cmd.inc>
#include <gm/radio/radio_cmd.inc>
#include <gm/marks/marks_cmd.inc>
#include <gm/graffity/g_cmd.inc>
#include <gm/weapons/w_cmd.inc>

#include <gm/tickets/tickets_cmd.inc>
#include <gm/corpse/crps_cmd.inc> 

#include <gm/phone/phone_cmd.inc>
#include <gm/payph/pp_cmd.inc>
#include <gm/pool/pool_cmd.inc>

#include <gm/anticheat/anti_cmd.inc>

#include <gm/vending/vending_cmd.inc>
