#include <gm/core/defines.inc> 
#include <gm/core/colors.inc>
#include <gm/core/macrosses.inc>

#include <gm/admin/admin_def.inc>
#include <gm/attach/attach_def.inc>

#include <gm/death/death_def.inc>

#include <gm/prop/h/house_def.inc>
#include <gm/prop/b/biz_def.inc>

#include <gm/prop/v/veh_def.inc>
#include <gm/prop/v/park_def.inc>
#include <gm/prop/f/furn_def.inc>

#include <gm/factions/f_def.inc>
#include <gm/factions/sasd/sasd_def.inc>

#include <gm/items/items_def.inc>

#include <gm/job/job_def.inc>
#include <gm/job/lamber/lam_def.inc>
#include <gm/job/miner/miner_def.inc>
#include <gm/job/trucker/trucker_def.inc>
#include <gm/job/fisher/fish_def.inc>

#include <gm/speedcam/sc_def.inc>
#include <gm/licenses/lic_def.inc>
#include <gm/login/login_def.inc>
#include <gm/graffity/g_def.inc>
#include <gm/sql/sql_def.inc>
#include <gm/weapons/w_def.inc>
 
#include <gm/phone/phone_def.inc>
#include <gm/phone/tow_def.inc>
#include <gm/payph/pp_def.inc>
#include <gm/pool/pool_def.inc>

#include <gm/factions/sasd/mdc_def.inc>

#include <gm/anticheat/anti_def.inc>







