#include <gm/attach/attach_dlg.inc>
#include <gm/boombox/box_dlg.inc>
#include <gm/bank/bank_dlg.inc>

#include <gm/factions/f_dlg.inc>
#include <gm/factions/docs/docs_dlg.inc>
#include <gm/factions/fd/fd_dlg.inc>
#include <gm/factions/mayor/m_dlg.inc>

#include <gm/factions/sasd/sasd_dlg.inc>
#include <gm/factions/sasd/mdc_dlg.inc>

#include <gm/food/food_dlg.inc>
#include <gm/inventory/inv_dlg.inc>

#include <gm/chopshop/chopshop_dlg.inc>
#include <gm/job/trucker/trucker_dlg.inc>

#include <gm/login/login_dlg.inc>
#include <gm/players/pl_dlg.inc>
#include <gm/billboard/bb_dlg.inc>
#include <gm/job/job_dlg.inc>
#include <gm/job/fisher/fish_dlg.inc>
#include <gm/gps/gps_dlg.inc>

#include <gm/prop/b/biz_dlg.inc>
#include <gm/prop/h/house_dlg.inc>
#include <gm/prop/v/veh_dlg.inc>
#include <gm/prop/f/furn_dlg.inc>

#include <gm/tickets/tickets_dlg.inc>
#include <gm/graffity/g_dlg.inc>

#include <gm/phone/phone_dlg.inc>

#include <gm/drugs/drugs_dlg.inc>

#include <gm/anticheat/anti_dlg.inc>
