#include <gm/anticheat/anti_enum.inc>

#include <gm/admin/admin_enum.inc>
#include <gm/attach/attach_enum.inc>
#include <gm/boombox/box_enum.inc>
#include <gm/bank/bank_enum.inc>
#include <gm/cctv/cctv_enum.inc>
#include <gm/death/death_enum.inc>
#include <gm/food/food_enum.inc>

#include <gm/factions/f_enum.inc>
#include <gm/factions/sasd/sasd_enum.inc>
#include <gm/factions/fd/fd_enum.inc>

#include <gm/prop/a/apart_enum.inc>
#include <gm/prop/b/biz_enum.inc>
#include <gm/prop/e/ent_enum.inc>
#include <gm/prop/g/garage_enum.inc>
#include <gm/prop/h/house_enum.inc>
#include <gm/prop/v/veh_enum.inc>

#include <gm/items/items_enum.inc>
#include <gm/job/trucker/trucker_enum.inc>

#include <gm/speedcam/sc_enum.inc>
#include <gm/notes/notes_enum.inc>
#include <gm/players/pl_enum.inc>
#include <gm/drugs/drugs_enum.inc>
#include <gm/gps/gps_enum.inc>

#include <gm/radio/radio_enum.inc>

#include <gm/tickets/tickets_enum.inc>

#include <gm/marks/marks_enum.inc>
#include <gm/graffity/g_enum.inc>

#include <gm/core/enum.inc> 
#include <gm/corpse/crps_enum.inc> 

#include <gm/pool/pool_enum.inc> 