#include <gm/core/keys.inc>
#include <gm/core/td.inc>

#include <gm/admin/admin.inc>
#include <gm/attach/attach.inc>
#include <gm/bank/bank.inc>
#include <gm/boombox/box.inc>
#include <gm/cctv/cctv.inc>
#include <gm/drugs/drugs.inc>
#include <gm/death/death.inc>

#include <gm/factions/f.inc>
#include <gm/factions/fd/fd.inc>

#include <gm/factions/sasd/sasd.inc>
#include <gm/factions/sasd/mdc.inc>
#include <gm/factions/sasd/radar.inc>

#include <gm/food/food.inc>
//#include <gm/death/death.inc>
//#include <gm/drugs/drugs.inc>
#include <gm/gps/gps.inc>
#include <gm/items/items.inc>

#include <gm/streets/streets.inc>

// #include <gm/job/fisher/fish.inc> co rôi
#include <gm/job/trash/trash.inc>
#include <gm/job/taxi/taxi.inc>
#include <gm/job/lamber/lam.inc>
#include <gm/job/miner/miner.inc>
#include <gm/job/trucker/trucker.inc>
#include <gm/job/job.inc>

#include <gm/speedcam/sc.inc>
#include <gm/licenses/lic.inc>
#include <gm/login/login.inc>

#include <gm/players/pl.inc>

#include <gm/prop/prop.inc>
#include <gm/prop/a/apart.inc>
#include <gm/prop/b/biz.inc>
#include <gm/prop/e/ent.inc>
#include <gm/prop/g/garage.inc>
#include <gm/prop/h/house.inc>
#include <gm/prop/v/veh.inc>

#include <gm/marks/marks.inc>
#include <gm/graffity/graffity.inc>

#include <gm/sql/sql.inc>

#include <gm/weapons/weap.inc>
#include <gm/weapons/shells.inc>

#include <gm/phone/phone.inc>
#include <gm/phone/towers.inc>
#include <gm/payph/pp.inc>

#include <gm/pool/pool.inc>

#include <gm/vending/vending.inc>

#include <gm/voicechat/voice.inc>