#include <gm/core/variables.inc>
#include <gm/core/tdraws/tdraw_var.inc>

#include <gm/animations/anim_var.inc>
#include <gm/players/pl_var.inc>

#include <gm/factions/sasd/sasd_var.inc>
#include <gm/factions/docs/docs_var.inc>
#include <gm/factions/fd/fd_var.inc>
#include <gm/factions/mayor/m_var.inc>

#include <gm/prop/b/biz_var.inc>
#include <gm/prop/g/garage_var.inc>
#include <gm/prop/v/veh_var.inc>

#include <gm/chopshop/chopshop_var.inc>

#include <gm/job/job_var.inc>
#include <gm/job/trash/trash_var.inc>
#include <gm/job/mech/mech_var.inc>
#include <gm/job/lamber/lam_var.inc>
#include <gm/job/miner/miner_var.inc>
#include <gm/job/taxi/taxi_var.inc>
#include <gm/job/fisher/fish_var.inc>
#include <gm/job/trucker/trucker_var.inc>

#include <gm/licenses/lic_var.inc>
#include <gm/login/login_var.inc>
#include <gm/sql/sql_var.inc>

#include <gm/billboard/bb_var.inc>
#include <gm/streets/st_var.inc>

#include <gm/pool/pool_var.inc>

#include <gm/vending/vending_var.inc>

#include <gm/voicechat/voice_var.inc>