#define SC_MIN_INSTALL      (5)     // The rank from which speed cameras can be installed
#define SC_DEF_SPEED        (90.0)  // Standard speed exceeding which a fine will be issued
#define SC_MAX_SPEED        (150)   // The maximum speed that the camera can càpture
#define SC_DEF_RADIUS       (20.0)  // The radius in which the camera will record violations
#define SC_DEF_TICKET_SUM   (500)   // Speeding fine
#define SC_DEF_TIME         (5)     // Time, when driving near the camera for the second or more times, during which a fine will not be issued